### ISSUE TITLE
Automating score extraction

### ISSUE THREAD

**Issue by ttuleyb** [hslarson/Moist-Meter#2]
Hey, have you automated the process of extracting the score from a video yet? I've created a script using OpenAI's API that allows the AI to read the relevant part of the transcript and extract the score, completely eliminating the need for human interaction.

The link to the github repo [Moist Scraper](https://github.com/ttuleyb/MoistScraper).

**Comment by hslarson** [comment]
This looks promising, thank you for the work you've done. One issue is that Charlie doesn't caption videos, and it takes a few hours for auto-generated captions to show up. I generally like to score videos within an hour or so. You could introduce a speech recognition program (or API) to get captions quicker, but at that point, you'd probably be better off making a purpose-built AI to score moist meters. This might actually be doable given that you have a dataset of 300+ moist meters that have already been scored; I'm not very knowledgeable on machine learning, so I'll leave that to you if you're interested.

Again, thank you for reaching out. Hopefully, OpenAI will make an API that can parse audio/video inputs soon, but at the moment, I'm not sure ChatGPT will meet my needs.

**Comment by ttuleyb** [comment]
Alright then, I think parsing audio would be wasteful as youtube already does so but if we wanted, we could use https://openai.com/blog/whisper/

Love the website, the automation may not be necessary if you rather prefer speed over automation as you mentioned. Nice talking to you.
